import { Link } from "@tanstack/react-router";
import { ArrowDownRight, ArrowUpRight, CalendarDays, Github, GraduationCap, Trophy, Users, Zap } from "lucide-react";
import { motion, useMotionValue, useScroll, useSpring, useTransform } from "motion/react";
import { useRef } from "react";

const principles = [
  ["01", "BUILD", "Ideas are cheap. Shipping is the skill."],
  ["02", "HACK", "Break the obvious path. Find a better one."],
  ["03", "COMPETE", "Walk into hackathons prepared, together."],
  ["04", "BELONG", "A room full of students who actually make things."],
];
const projects = [
  ["MAYAVIHIN", "AI / ML", "Deepfake detection"],
  ["SYNQRO", "SAAS", "Digital queue intelligence"],
  ["CLEANFLOW", "CIVIC TECH", "Fleet management"],
  ["SEEKHSATHI", "EDTECH", "Skill exchange"],
];
const ticker = ["CODEBLOODED", "BUILD / HACK / INNOVATE", "COLLEGE TECH CLUB", "SHIP SOMETHING", "2026"];

function MagneticButton({ children }: { children: React.ReactNode }) {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const sx = useSpring(x, { stiffness: 360, damping: 24 });
  const sy = useSpring(y, { stiffness: 360, damping: 24 });
  return <Link to="/join" onPointerMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); x.set((e.clientX - r.left - r.width / 2) * 0.18); y.set((e.clientY - r.top - r.height / 2) * 0.18); }} onPointerLeave={() => { x.set(0); y.set(0); }}><motion.span style={{ x: sx, y: sy }} whileTap={{ scale: 0.96 }} className="inline-flex items-center gap-3 rounded-full bg-foreground px-6 py-3 font-display text-xs font-black uppercase tracking-[0.16em] text-background shadow-xl">{children}</motion.span></Link>;
}

export function HomePage() {
  const heroRef = useRef<HTMLElement>(null);
  const storyRef = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ["start start", "end start"] });
  const { scrollYProgress: storyProgress } = useScroll({ target: storyRef, offset: ["start end", "end start"] });
  const heroY = useTransform(scrollYProgress, [0, 1], [0, 240]);
  const heroScale = useTransform(scrollYProgress, [0, 1], [1, 0.82]);
  const heroRotate = useTransform(scrollYProgress, [0, 1], [0, -2]);
  const storyX = useTransform(storyProgress, [0, 1], [90, -90]);

  return <div className="cb-editorial overflow-hidden bg-background">
    <section ref={heroRef} className="relative min-h-[calc(100vh-5rem)] overflow-hidden border-b-2 border-foreground/10 bg-[#9cc8e8] text-[#11131a]" data-ocid="hero-section">
      <div className="cb-sun absolute -right-24 top-10 h-72 w-72 rounded-full bg-[#f8d6dc] blur-[1px]" />
      <motion.div style={{ y: heroY, scale: heroScale, rotate: heroRotate }} className="relative z-10 mx-auto flex min-h-[calc(100vh-5rem)] max-w-[1500px] flex-col justify-between px-5 pb-10 pt-8 sm:px-10 lg:px-14">
        <div className="flex items-start justify-between font-mono text-[9px] uppercase tracking-[0.24em]"><span className="rounded-full border border-[#11131a]/30 px-3 py-1">CB / 001</span><span className="hidden sm:block">College hackers · builders · misfits</span><span>2026 ↘</span></div>
        <div className="relative py-16 sm:py-20">
          <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} className="mb-7 flex items-center gap-3 font-mono text-[9px] uppercase tracking-[0.24em]"><span className="h-2 w-2 rounded-full bg-[#f04f91]" /> Student-led technology club</motion.div>
          <div className="relative">
            <motion.h1 initial={{ y: "100%" }} animate={{ y: 0 }} transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }} className="cb-title font-display text-[19vw] font-black uppercase leading-[0.72] tracking-[-0.09em] sm:text-[17vw] lg:text-[13.5vw]">CODE</motion.h1>
            <motion.h1 initial={{ y: "100%" }} animate={{ y: 0 }} transition={{ duration: 1, delay: 0.1, ease: [0.16, 1, 0.3, 1] }} className="cb-title cb-outline ml-[7vw] font-display text-[19vw] font-black uppercase leading-[0.72] tracking-[-0.09em] sm:text-[17vw] lg:text-[13.5vw]">BLOODED</motion.h1>
            <motion.div animate={{ rotate: [2, -2, 2], y: [0, -8, 0] }} transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }} className="absolute right-[5%] top-[28%] hidden w-48 rotate-2 border-2 border-[#11131a] bg-[#f7f2e7] p-4 shadow-[10px_10px_0_#11131a] sm:block lg:w-64"><div className="font-mono text-[8px] uppercase tracking-[0.18em]">FIELD NOTE / 07</div><p className="mt-5 font-display text-2xl font-black uppercase leading-[0.88]">DON'T<br />WAIT<br />FOR<br />PERMISSION.</p><div className="mt-5 h-1 w-12 bg-[#f04f91]" /></motion.div>
          </div>
          <div className="mt-9 grid gap-6 sm:grid-cols-[1fr_auto] sm:items-end"><p className="max-w-xl text-lg font-medium leading-relaxed sm:text-xl">A college hackathon club for students who want to turn <span className="font-black underline decoration-[#f04f91] decoration-4 underline-offset-4">curiosity into shipped work.</span></p><MagneticButton>Enter the club <ArrowUpRight className="h-4 w-4" /></MagneticButton></div>
        </div>
        <div className="flex items-end justify-between border-t border-[#11131a]/30 pt-4 font-mono text-[8px] uppercase tracking-[0.22em]"><span>Scroll / explore / participate</span><motion.span animate={{ y: [0, 7, 0] }} transition={{ duration: 1.2, repeat: Infinity }}><ArrowDownRight className="h-5 w-5" /></motion.span><span className="hidden sm:block">Build different.</span></div>
      </motion.div>
    </section>

    <section className="overflow-hidden border-b-2 border-foreground/10 bg-[#f04f91] py-4 text-[#11131a]" data-ocid="ticker-section"><motion.div style={{ x: storyX }} className="flex w-max items-center gap-10 whitespace-nowrap font-display text-2xl font-black uppercase tracking-[-0.03em] sm:text-4xl">{[...ticker, ...ticker, ...ticker].map((item, i) => <span key={`${item}-${i}`} className="flex items-center gap-10">{item}<span className="text-[#f7f2e7]">✳</span></span>)}</motion.div></section>

    <section ref={storyRef} className="relative border-b-2 border-foreground/10 bg-[#f7f2e7] px-5 py-24 sm:px-10 lg:px-14" data-ocid="story-section"><div className="mx-auto max-w-[1400px]">
      <div className="grid gap-12 lg:grid-cols-[0.45fr_1.55fr]"><div className="font-mono text-[9px] uppercase tracking-[0.24em] text-foreground/55">Manifesto / 002</div><div><motion.h2 initial={{ opacity: 0, y: 50 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.35 }} transition={{ duration: 0.75 }} className="font-display text-5xl font-black uppercase leading-[0.86] tracking-[-0.065em] sm:text-7xl lg:text-8xl">WE DON'T<br /><span className="text-[#f04f91]">DO BORING.</span></motion.h2><p className="mt-9 max-w-3xl text-lg leading-relaxed text-foreground/70 sm:text-2xl">CodeBlooded is the part of college where the lecture ends and the interesting stuff starts: late-night builds, chaotic prototypes, hackathon war rooms, new friends and the occasional idea that refuses to die.</p></div></div>
      <div className="mt-20 grid border-2 border-foreground/15 md:grid-cols-2 xl:grid-cols-4">{principles.map(([number, title, body], i) => <motion.article key={number} initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: i * 0.08, duration: 0.6 }} whileHover={{ y: -8, rotate: i % 2 ? 1 : -1 }} className="group min-h-[300px] border-b-2 border-foreground/15 bg-[#f7f2e7] p-7 last:border-b-0 md:border-r-2 md:last:border-r-0 xl:border-b-0"><div className="flex justify-between font-mono text-[9px] uppercase tracking-[0.2em]"><span>{number}</span><Zap className="h-4 w-4 transition-transform group-hover:rotate-45" /></div><div className="mt-24"><h3 className="font-display text-3xl font-black uppercase tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-foreground/60">{body}</p></div></motion.article>)}</div>
    </div></section>

    <section className="relative overflow-hidden border-b-2 border-foreground/10 bg-[#a8d1ec] px-5 py-24 sm:px-10 lg:px-14" data-ocid="experience-section"><div className="mx-auto max-w-[1400px]"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="font-mono text-[9px] uppercase tracking-[0.24em]">The loop / 003</p><h2 className="mt-4 font-display text-6xl font-black uppercase leading-[0.78] tracking-[-0.07em] sm:text-8xl">MAKE.<br />BREAK.<br />REPEAT.</h2></div><div className="max-w-md text-sm leading-relaxed text-foreground/65">Workshops. Hackathons. Projects. Chess. Demos. Community. The website is only the front door — the real club lives in the things we build together.</div></div>
      <div className="relative mt-20 min-h-[560px]"><motion.div initial={{ rotate: -5, y: 30, opacity: 0 }} whileInView={{ rotate: -5, y: 0, opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.8 }} className="absolute left-[2%] top-0 w-[70%] max-w-[680px] border-2 border-foreground/20 bg-[#f7f2e7] p-7 shadow-[14px_14px_0_rgba(17,19,26,.12)] sm:p-10"><div className="flex justify-between border-b-2 border-foreground pb-4 font-mono text-[8px] uppercase tracking-[0.18em]"><span>CODEBLOODED / ACTIVITY LOG</span><span>01—04</span></div><div className="mt-10 grid grid-cols-[auto_1fr] gap-6"><span className="font-display text-7xl font-black leading-none text-[#f04f91]">01</span><div><h3 className="font-display text-4xl font-black uppercase leading-[0.86]">WORKSHOPS<br />THAT SHIP.</h3><p className="mt-4 max-w-sm text-sm text-foreground/60">Learn a thing. Break a thing. Build the version you wish existed.</p></div></div><div className="mt-10 flex flex-wrap gap-2">{["AI", "WEB", "CLOUD", "SYSTEMS", "OPEN SOURCE"].map((x) => <span key={x} className="border border-foreground/20 px-2 py-1 font-mono text-[8px]">{x}</span>)}</div></motion.div><motion.div initial={{ rotate: 6, y: 50, opacity: 0 }} whileInView={{ rotate: 6, y: 0, opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.8, delay: 0.15 }} className="absolute right-0 top-36 w-[68%] max-w-[640px] border-2 border-foreground/15 bg-[#f04f91] p-7 text-[#11131a] shadow-[14px_14px_0_rgba(17,19,26,.12)] sm:p-10"><div className="font-mono text-[8px] uppercase tracking-[0.2em]">02 / HACKATHON MODE</div><h3 className="mt-10 font-display text-6xl font-black uppercase leading-[0.78] tracking-[-0.06em]">48H<br />OF<br />MAYHEM.</h3><div className="mt-10 flex items-end justify-between"><p className="max-w-xs text-sm">Teams, caffeine, bad ideas becoming good ones and something deployed before sunrise.</p><Trophy className="h-14 w-14" /></div></motion.div></div>
    </div></section>

    <section className="border-b-2 border-foreground/10 bg-[#f7f2e7] px-5 py-24 sm:px-10 lg:px-14" data-ocid="projects-section"><div className="mx-auto max-w-[1400px]"><div className="mb-14 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="font-mono text-[9px] uppercase tracking-[0.24em]">Things we've made / 004</p><h2 className="mt-4 font-display text-6xl font-black uppercase leading-[0.8] tracking-[-0.07em] sm:text-8xl">RECENT<br />SHIPS.</h2></div><ArrowDownRight className="hidden h-16 w-16 lg:block" /></div><div className="grid gap-5 md:grid-cols-2">{projects.map(([name, tag, description], i) => <motion.article key={name} initial={{ opacity: 0, scale: 0.94, y: 35 }} whileInView={{ opacity: 1, scale: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: i * 0.07, duration: 0.65 }} whileHover={{ y: -10 }} className={`group relative min-h-[330px] overflow-hidden border-2 border-foreground/15 p-7 sm:p-9 ${i % 2 === 0 ? "bg-[#9cc8e8]" : "bg-[#f04f91]"}`} data-ocid={`project-card-${i}`}><motion.div animate={{ rotate: [0, 8, 0], scale: [1, 1.08, 1] }} transition={{ duration: 7 + i, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-16 -top-16 h-48 w-48 rounded-full border-[28px] border-foreground/10" /><div className="relative flex h-full flex-col justify-between"><div className="flex justify-between"><span className="font-mono text-[8px] uppercase tracking-[0.2em]">{tag}</span><span className="font-mono text-[8px]">0{i + 1}</span></div><div><h3 className="font-display text-5xl font-black uppercase leading-[0.82] tracking-[-0.06em] sm:text-6xl">{name}</h3><p className="mt-4 max-w-sm text-sm text-foreground/65">{description}</p></div><div className="flex justify-between border-t border-foreground/20 pt-4 font-mono text-[8px] uppercase tracking-[0.16em]"><span>Student-built</span><ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div></div></motion.article>)}</div></div></section>

    <section className="overflow-hidden border-b-2 border-foreground/10 bg-[#8ebce0] px-5 py-24 sm:px-10 lg:px-14" data-ocid="club-life-section"><div className="mx-auto max-w-[1400px]"><div className="grid gap-10 lg:grid-cols-[1fr_1fr] lg:items-center"><div><p className="font-mono text-[9px] uppercase tracking-[0.24em]">Club life / 005</p><h2 className="mt-5 font-display text-6xl font-black uppercase leading-[0.78] tracking-[-0.07em] sm:text-8xl">FIND<br />YOUR<br /><span className="text-[#f04f91]">PEOPLE.</span></h2></div><motion.div initial={{ rotate: 5, opacity: 0, x: 60 }} whileInView={{ rotate: 2, opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.8 }} className="border-2 border-foreground bg-[#f7f2e7] p-8 shadow-[16px_16px_0_#11131a]"><div className="flex items-center justify-between font-mono text-[8px] uppercase tracking-[0.18em]"><span>WHO'S IN THE ROOM?</span><Users className="h-4 w-4" /></div><div className="mt-8 space-y-5">{[["BUILDERS", "People who make prototypes at 2AM"], ["HACKERS", "People who love impossible constraints"], ["DESIGNERS", "People who make the impossible look good"], ["CURIOUS", "People who just want to learn"]].map(([a, b], i) => <motion.div key={a} initial={{ opacity: 0, x: -15 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }} className="flex gap-4 border-b border-foreground/15 pb-4"><span className="font-mono text-[8px] text-[#f04f91]">0{i + 1}</span><div><div className="font-display text-xl font-black uppercase">{a}</div><div className="mt-1 text-xs text-foreground/55">{b}</div></div></motion.div>)}</div></motion.div></div></div></section>

    <section className="relative overflow-hidden bg-[#f04f91] px-5 py-28 text-[#11131a] sm:px-10 lg:px-14" data-ocid="join-section"><div className="absolute -right-20 top-0 h-96 w-96 rounded-full border-[60px] border-[#f7f2e7]/20" /><div className="relative mx-auto max-w-[1400px]"><div className="font-mono text-[9px] uppercase tracking-[0.24em]">Recruitment / 006</div><h2 className="mt-7 max-w-6xl font-display text-[16vw] font-black uppercase leading-[0.72] tracking-[-0.09em] sm:text-[12vw]">JOIN<br />THE<br />LOOP.</h2><div className="mt-10 flex flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-lg text-lg font-medium leading-relaxed">No experience required. No perfect resume required. Just curiosity, consistency and the willingness to make something.</p><MagneticButton>Apply to CodeBlooded <ArrowUpRight className="h-4 w-4" /></MagneticButton></div></div></section>

    <section className="bg-[#11131a] px-5 py-10 text-[#f7f2e7] sm:px-10 lg:px-14" data-ocid="footer-grid"><div className="mx-auto grid max-w-[1400px] gap-10 md:grid-cols-3"><div><div className="font-display text-4xl font-black tracking-[-0.06em]">CODEBLOODED<span className="text-[#f04f91]">.</span></div><p className="mt-3 max-w-xs text-sm text-white/50">A college tech club for builders, hackers and the relentlessly curious.</p></div><div className="grid grid-cols-2 gap-4 font-mono text-[9px] uppercase tracking-[0.18em]"><Link to="/join" className="hover:text-[#f04f91]">Join</Link><Link to="/calendar" className="hover:text-[#f04f91]">Calendar</Link><Link to="/chess" className="hover:text-[#f04f91]">Chess</Link><Link to="/chessbot" className="hover:text-[#f04f91]">Bot</Link></div><div className="flex gap-3 md:justify-end"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-white/20"><Github className="h-4 w-4" /></span><span className="flex h-10 w-10 items-center justify-center rounded-full border border-white/20"><CalendarDays className="h-4 w-4" /></span><span className="flex h-10 w-10 items-center justify-center rounded-full border border-white/20"><GraduationCap className="h-4 w-4" /></span></div></div><div className="mx-auto mt-12 flex max-w-[1400px] justify-between border-t border-white/10 pt-5 font-mono text-[8px] uppercase tracking-[0.2em] text-white/40"><span>© 2026 CodeBlooded</span><span>Built by students / for students</span></div></section>
  </div>;
}
