/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'reasonForJoining' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'priorExperience' : IDL.Text,
  'yearOfStudy' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'deleteApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmitResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'reasonForJoining' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'priorExperience' : IDL.Text,
    'yearOfStudy' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'deleteApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmitResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };