/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'reasonForJoining' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'phone' : string,
  'department' : string,
  'priorExperience' : string,
  'yearOfStudy' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null };
export interface CalendarEvent {
  'id' : bigint,
  'subject' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'time' : string,
  'description' : string,
  'category' : string,
}
export interface ChessPlayer {
  'username' : string,
  'playerId' : string,
  'createdAt' : Timestamp,
}
export interface ChessScore {
  'result' : string,
  'playerId' : string,
  'createdAt' : Timestamp,
  'botName' : string,
  'score' : bigint,
  'movesCount' : bigint,
}
export type ChessScoreResult = { 'ok' : null } |
  { 'err' : string };
export interface CreateEventInput {
  'subject' : string,
  'date' : string,
  'time' : string,
  'description' : string,
  'category' : string,
}
export type CreateResult = { 'ok' : string } |
  { 'err' : string };
export type SubmitResult = { 'ok' : bigint } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'approveApplication' : ActorMethod<[bigint], boolean>,
  'createChessPlayer' : ActorMethod<[string], CreateResult>,
  'createEvent' : ActorMethod<[CreateEventInput], bigint>,
  'deleteApplication' : ActorMethod<[bigint], boolean>,
  'deleteChessPlayer' : ActorMethod<[string], boolean>,
  'deleteEvent' : ActorMethod<[bigint], boolean>,
  'getApplications' : ActorMethod<[], Array<Application>>,
  'getChessLeaderboard' : ActorMethod<[], Array<ChessScore>>,
  'getChessPlayers' : ActorMethod<[], Array<ChessPlayer>>,
  'getChessScores' : ActorMethod<[], Array<ChessScore>>,
  'getEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string, string, string],
    SubmitResult
  >,
  'submitChessScore' : ActorMethod<
    [string, string, bigint, string, bigint],
    ChessScoreResult
  >,
  'updateEvent' : ActorMethod<[bigint, CreateEventInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];