/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const CreateEventInput = IDL.Record({
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'reasonForJoining' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'priorExperience' : IDL.Text,
  'yearOfStudy' : IDL.Text,
});
export const ChessScore = IDL.Record({
  'result' : IDL.Text,
  'playerId' : IDL.Text,
  'createdAt' : Timestamp,
  'botName' : IDL.Text,
  'score' : IDL.Nat,
  'movesCount' : IDL.Nat,
});
export const ChessPlayer = IDL.Record({
  'username' : IDL.Text,
  'playerId' : IDL.Text,
  'createdAt' : Timestamp,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const ChessScoreResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'approveApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createChessPlayer' : IDL.Func([IDL.Text], [CreateResult], []),
  'createEvent' : IDL.Func([CreateEventInput], [IDL.Nat], []),
  'deleteApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChessPlayer' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getChessLeaderboard' : IDL.Func([], [IDL.Vec(ChessScore)], ['query']),
  'getChessPlayers' : IDL.Func([], [IDL.Vec(ChessPlayer)], ['query']),
  'getChessScores' : IDL.Func([], [IDL.Vec(ChessScore)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmitResult],
      [],
    ),
  'submitChessScore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [ChessScoreResult],
      [],
    ),
  'updateEvent' : IDL.Func([IDL.Nat, CreateEventInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const CreateEventInput = IDL.Record({
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'reasonForJoining' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'priorExperience' : IDL.Text,
    'yearOfStudy' : IDL.Text,
  });
  const ChessScore = IDL.Record({
    'result' : IDL.Text,
    'playerId' : IDL.Text,
    'createdAt' : Timestamp,
    'botName' : IDL.Text,
    'score' : IDL.Nat,
    'movesCount' : IDL.Nat,
  });
  const ChessPlayer = IDL.Record({
    'username' : IDL.Text,
    'playerId' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const ChessScoreResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'approveApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createChessPlayer' : IDL.Func([IDL.Text], [CreateResult], []),
    'createEvent' : IDL.Func([CreateEventInput], [IDL.Nat], []),
    'deleteApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChessPlayer' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getChessLeaderboard' : IDL.Func([], [IDL.Vec(ChessScore)], ['query']),
    'getChessPlayers' : IDL.Func([], [IDL.Vec(ChessPlayer)], ['query']),
    'getChessScores' : IDL.Func([], [IDL.Vec(ChessScore)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmitResult],
        [],
      ),
    'submitChessScore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [ChessScoreResult],
        [],
      ),
    'updateEvent' : IDL.Func([IDL.Nat, CreateEventInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };