/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'reasonForJoining' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'phone' : string,
  'department' : string,
  'priorExperience' : string,
  'yearOfStudy' : string,
}
export type SubmitResult = { 'ok' : bigint } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'deleteApplication' : ActorMethod<[bigint], boolean>,
  'getApplications' : ActorMethod<[], Array<Application>>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string, string, string],
    SubmitResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];