/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SubmitResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export interface CreateEventInput {
    subject: string;
    date: string;
    time: string;
    description: string;
    category: string;
}
export interface CalendarEvent {
    id: bigint;
    subject: string;
    date: string;
    createdAt: Timestamp;
    time: string;
    description: string;
    category: string;
}
export type ChessScoreResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface ChessPlayer {
    username: string;
    playerId: string;
    createdAt: Timestamp;
}
export interface Application {
    id: bigint;
    status: ApplicationStatus;
    reasonForJoining: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    phone: string;
    department: string;
    priorExperience: string;
    yearOfStudy: string;
}
export interface ChessScore {
    result: string;
    playerId: string;
    createdAt: Timestamp;
    botName: string;
    score: bigint;
    movesCount: bigint;
}
export type CreateResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export enum ApplicationStatus {
    pending = "pending",
    approved = "approved"
}
export interface backendInterface {
    approveApplication(id: bigint): Promise<boolean>;
    createChessPlayer(username: string): Promise<CreateResult>;
    createEvent(input: CreateEventInput): Promise<bigint>;
    deleteApplication(id: bigint): Promise<boolean>;
    deleteChessPlayer(playerId: string): Promise<boolean>;
    deleteEvent(id: bigint): Promise<boolean>;
    getApplications(): Promise<Array<Application>>;
    getChessLeaderboard(): Promise<Array<ChessScore>>;
    getChessPlayers(): Promise<Array<ChessPlayer>>;
    getChessScores(): Promise<Array<ChessScore>>;
    getEvents(): Promise<Array<CalendarEvent>>;
    submitApplication(name: string, email: string, phone: string, yearOfStudy: string, department: string, reasonForJoining: string, priorExperience: string): Promise<SubmitResult>;
    submitChessScore(playerId: string, botName: string, score: bigint, result: string, movesCount: bigint): Promise<ChessScoreResult>;
    updateEvent(id: bigint, input: CreateEventInput): Promise<boolean>;
}
import type { Application as _Application, ApplicationStatus as _ApplicationStatus, ChessScoreResult as _ChessScoreResult, CreateResult as _CreateResult, SubmitResult as _SubmitResult, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveApplication(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplication(arg0);
            return result;
        }
    }
    async createChessPlayer(arg0: string): Promise<CreateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createChessPlayer(arg0);
                return from_candid_CreateResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChessPlayer(arg0);
            return from_candid_CreateResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEvent(arg0: CreateEventInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async deleteApplication(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApplication(arg0);
            return result;
        }
    }
    async deleteChessPlayer(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChessPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChessPlayer(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async getApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplications();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplications();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChessLeaderboard(): Promise<Array<ChessScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChessLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChessLeaderboard();
            return result;
        }
    }
    async getChessPlayers(): Promise<Array<ChessPlayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChessPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChessPlayers();
            return result;
        }
    }
    async getChessScores(): Promise<Array<ChessScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChessScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChessScores();
            return result;
        }
    }
    async getEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return result;
        }
    }
    async submitApplication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<SubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_SubmitResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_SubmitResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitChessScore(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint): Promise<ChessScoreResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitChessScore(arg0, arg1, arg2, arg3, arg4);
                return from_candid_ChessScoreResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitChessScore(arg0, arg1, arg2, arg3, arg4);
            return from_candid_ChessScoreResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEvent(arg0: bigint, arg1: CreateEventInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ChessScoreResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChessScoreResult): ChessScoreResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_CreateResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateResult): CreateResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitResult): SubmitResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    reasonForJoining: string;
    name: string;
    submittedAt: _Timestamp;
    email: string;
    phone: string;
    department: string;
    priorExperience: string;
    yearOfStudy: string;
}): {
    id: bigint;
    status: ApplicationStatus;
    reasonForJoining: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    phone: string;
    department: string;
    priorExperience: string;
    yearOfStudy: string;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n6(_uploadFile, _downloadFile, value.status),
        reasonForJoining: value.reasonForJoining,
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        phone: value.phone,
        department: value.department,
        priorExperience: value.priorExperience,
        yearOfStudy: value.yearOfStudy
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "approved" in value ? ApplicationStatus.approved : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
import { mockBackend } from './mocks/backend';

export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): backendInterface {
    return mockBackend;
}
