/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SubmitResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export type SkinResult = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface Application {
    id: bigint;
    status: ApplicationStatus;
    reasonForJoining: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    phone: string;
    department: string;
    priorExperience: string;
    yearOfStudy: string;
}
export interface GamePlayer {
    username: string;
    playerId: string;
    createdAt: Timestamp;
    passwordHash: string;
}
export type AchievementResult = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface PlayerRank {
    username: string;
    playerId: string;
    rank: bigint;
    score: bigint;
}
export type RegisterResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface CreateEventInput {
    subject: string;
    date: string;
    time: string;
    description: string;
    category: string;
}
export interface CalendarEvent {
    id: bigint;
    subject: string;
    date: string;
    createdAt: Timestamp;
    time: string;
    description: string;
    category: string;
}
export interface PlayerAchievement {
    achievementId: string;
    unlockedAt: bigint;
    playerId: string;
}
export type SubmitScoreResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface PlayerSkin {
    unlockedAt: bigint;
    playerId: string;
    equipped: boolean;
    skinId: string;
}
export type LoginResult = {
    __kind__: "ok";
    ok: GamePlayer;
} | {
    __kind__: "err";
    err: string;
};
export interface GameScore {
    playerId: string;
    achievedAt: Timestamp;
    gameId: string;
    wavesCleared: bigint;
    scoreId: string;
    score: bigint;
    killedEnemies: bigint;
}
export enum ApplicationStatus {
    pending = "pending",
    approved = "approved"
}
export interface backendInterface {
    approveApplication(id: bigint): Promise<boolean>;
    createEvent(input: CreateEventInput): Promise<bigint>;
    deleteApplication(id: bigint): Promise<boolean>;
    deleteEvent(id: bigint): Promise<boolean>;
    deleteGamePlayer(playerId: string): Promise<boolean>;
    deleteGameScore(scoreId: string): Promise<boolean>;
    equipSkin(playerId: string, skinId: string): Promise<SkinResult>;
    getAllGameScores(): Promise<Array<GameScore>>;
    getApplications(): Promise<Array<Application>>;
    getEquippedSkin(playerId: string): Promise<PlayerSkin | null>;
    getEvents(): Promise<Array<CalendarEvent>>;
    getGamePlayers(): Promise<Array<GamePlayer>>;
    getGrandLeaderboard(limit: bigint): Promise<Array<PlayerRank>>;
    getPlayerAchievements(playerId: string): Promise<Array<PlayerAchievement>>;
    getPlayerRank(gameId: string, playerId: string): Promise<PlayerRank | null>;
    getPlayerSkins(playerId: string): Promise<Array<PlayerSkin>>;
    getTopScores(gameId: string, limit: bigint): Promise<Array<GameScore>>;
    loginGamePlayer(username: string, password: string): Promise<LoginResult>;
    registerGamePlayer(username: string, password: string): Promise<RegisterResult>;
    submitApplication(name: string, email: string, phone: string, yearOfStudy: string, department: string, reasonForJoining: string, priorExperience: string): Promise<SubmitResult>;
    submitGameScore(playerId: string, gameId: string, score: bigint, kills: bigint, waves: bigint): Promise<SubmitScoreResult>;
    unlockAchievement(playerId: string, achievementId: string): Promise<AchievementResult>;
    unlockSkin(playerId: string, skinId: string): Promise<SkinResult>;
    updateEvent(id: bigint, input: CreateEventInput): Promise<boolean>;
}
import type { AchievementResult as _AchievementResult, Application as _Application, ApplicationStatus as _ApplicationStatus, GamePlayer as _GamePlayer, LoginResult as _LoginResult, PlayerRank as _PlayerRank, PlayerSkin as _PlayerSkin, RegisterResult as _RegisterResult, SkinResult as _SkinResult, SubmitResult as _SubmitResult, SubmitScoreResult as _SubmitScoreResult, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveApplication(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplication(arg0);
            return result;
        }
    }
    async createEvent(arg0: CreateEventInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async deleteApplication(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApplication(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteGamePlayer(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGamePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGamePlayer(arg0);
            return result;
        }
    }
    async deleteGameScore(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGameScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGameScore(arg0);
            return result;
        }
    }
    async equipSkin(arg0: string, arg1: string): Promise<SkinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.equipSkin(arg0, arg1);
                return from_candid_SkinResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.equipSkin(arg0, arg1);
            return from_candid_SkinResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGameScores(): Promise<Array<GameScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGameScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGameScores();
            return result;
        }
    }
    async getApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplications();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplications();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEquippedSkin(arg0: string): Promise<PlayerSkin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquippedSkin(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquippedSkin(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return result;
        }
    }
    async getGamePlayers(): Promise<Array<GamePlayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGamePlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGamePlayers();
            return result;
        }
    }
    async getGrandLeaderboard(arg0: bigint): Promise<Array<PlayerRank>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrandLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrandLeaderboard(arg0);
            return result;
        }
    }
    async getPlayerAchievements(arg0: string): Promise<Array<PlayerAchievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerAchievements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerAchievements(arg0);
            return result;
        }
    }
    async getPlayerRank(arg0: string, arg1: string): Promise<PlayerRank | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRank(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRank(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerSkins(arg0: string): Promise<Array<PlayerSkin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerSkins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerSkins(arg0);
            return result;
        }
    }
    async getTopScores(arg0: string, arg1: bigint): Promise<Array<GameScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScores(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScores(arg0, arg1);
            return result;
        }
    }
    async loginGamePlayer(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginGamePlayer(arg0, arg1);
                return from_candid_LoginResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginGamePlayer(arg0, arg1);
            return from_candid_LoginResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerGamePlayer(arg0: string, arg1: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerGamePlayer(arg0, arg1);
                return from_candid_RegisterResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerGamePlayer(arg0, arg1);
            return from_candid_RegisterResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitApplication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<SubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_SubmitResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_SubmitResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitGameScore(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<SubmitScoreResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGameScore(arg0, arg1, arg2, arg3, arg4);
                return from_candid_SubmitScoreResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGameScore(arg0, arg1, arg2, arg3, arg4);
            return from_candid_SubmitScoreResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlockAchievement(arg0: string, arg1: string): Promise<AchievementResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAchievement(arg0, arg1);
                return from_candid_AchievementResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAchievement(arg0, arg1);
            return from_candid_AchievementResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlockSkin(arg0: string, arg1: string): Promise<SkinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockSkin(arg0, arg1);
                return from_candid_SkinResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockSkin(arg0, arg1);
            return from_candid_SkinResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEvent(arg0: bigint, arg1: CreateEventInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AchievementResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementResult): AchievementResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SkinResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkinResult): SkinResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitResult): SubmitResult {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitScoreResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitScoreResult): SubmitScoreResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerSkin]): PlayerSkin | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerRank]): PlayerRank | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    reasonForJoining: string;
    name: string;
    submittedAt: _Timestamp;
    email: string;
    phone: string;
    department: string;
    priorExperience: string;
    yearOfStudy: string;
}): {
    id: bigint;
    status: ApplicationStatus;
    reasonForJoining: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    phone: string;
    department: string;
    priorExperience: string;
    yearOfStudy: string;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n6(_uploadFile, _downloadFile, value.status),
        reasonForJoining: value.reasonForJoining,
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        phone: value.phone,
        department: value.department,
        priorExperience: value.priorExperience,
        yearOfStudy: value.yearOfStudy
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GamePlayer;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GamePlayer;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "approved" in value ? ApplicationStatus.approved : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
